/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    id("com.gradleup.shadow") version "8.3.6"
    id("de.eldoria.plugin-yml.paper") version "0.7.1"
}
paper {
    main = "org.example.Example"
    authors = listOf("Fair")
    apiVersion = "1.21"
    version = "0.0.1"
}

tasks {
    register<Copy>("copyToServer") {
        from(shadowJar)
        destinationDir = File("server/plugins")
    }
    build {
        dependsOn(shadowJar)
    }
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    implementation(project(":lib"))
        // https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation("org.slf4j:slf4j-api:2.0.17")

    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")


    implementation("io.github.classgraph:classgraph:4.8.184")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
